# Generated by Django 2.0 on 2020-11-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('channel_main', models.IntegerField()),
            ],
            options={
                'db_table': 'ygj_channel',
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.BigIntegerField()),
                ('channel', models.IntegerField()),
                ('title', models.IntegerField()),
                ('mark', models.CharField(max_length=100)),
                ('promoter', models.IntegerField()),
                ('consult', models.IntegerField(blank=True, null=True)),
                ('active', models.IntegerField(blank=True, null=True)),
                ('submit_time', models.DateField()),
                ('up_time', models.DateField()),
                ('distribute_time', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ygj_form',
            },
        ),
    ]
