# Generated by Django 2.0 on 2020-11-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turnover',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.IntegerField()),
                ('turnover', models.CharField(max_length=50)),
                ('channel_main', models.IntegerField()),
                ('consult', models.IntegerField()),
                ('title', models.IntegerField()),
                ('time', models.DateField()),
            ],
            options={
                'db_table': 'ygj_turnover',
            },
        ),
    ]
